const SONGS = [
  {
    "id": "29",
    "rank": 1,
    "prev": 29,
    "isNew": false,
    "title": "Minnow Nesh",
    "artist": "Hachalu Hundessa",
    "country": "Ethiopia",
    "lang": "Oromo",
    "region_language": "Oromo",
    "genre": "Oromo Pop",
    "views": 8200000,
    "weekViews": 42000,
    "year": 2021,
    "ytId": "2ixjSHqHqpU",
    "thumbUrl": "https://i.ytimg.com/vi/2ixjSHqHqpU/maxresdefault.jpg",
    "spotifyId": null,
    "reason": "8.2M views — beloved Oromo anthem.",
    "score": 68
  },
  {
    "id": "30",
    "rank": 2,
    "prev": 30,
    "isNew": false,
    "title": "Sabbata",
    "artist": "Dawit Tsige",
    "country": "Ethiopia",
    "lang": "Oromo",
    "region_language": "Oromo",
    "genre": "Oromo Pop",
    "views": 6100000,
    "weekViews": 38000,
    "year": 2022,
    "ytId": "Gk6ZkJoFBnE",
    "thumbUrl": "https://i.ytimg.com/vi/Gk6ZkJoFBnE/maxresdefault.jpg",
    "spotifyId": null,
    "reason": "6.1M views — top Oromo pop track.",
    "score": 67
  },
  {
    "id": "e11",
    "rank": 3,
    "prev": 11,
    "isNew": false,
    "title": "Libi Zbele",
    "artist": "Helen Meles",
    "country": "Ethiopia",
    "lang": "Tigrinya",
    "region_language": "Tigrigna",
    "genre": "Tigrinya Pop",
    "views": 4200000,
    "weekViews": 32000,
    "year": 2024,
    "ytId": "Q0wH8GVbRfY",
    "thumbUrl": "https://i.ytimg.com/vi/Q0wH8GVbRfY/maxresdefault.jpg",
    "spotifyId": null,
    "reason": "4.2M views.",
    "score": 80
  },
  {
    "id": "31",
    "rank": 4,
    "prev": 31,
    "isNew": false,
    "title": "Siifan Jira",
    "artist": "Caalaa Bultumee",
    "country": "Ethiopia",
    "lang": "Oromo",
    "region_language": "Oromo",
    "genre": "Oromo Pop",
    "views": 4500000,
    "weekViews": 30000,
    "year": 2023,
    "ytId": "QxNe3k0b9EU",
    "thumbUrl": "https://i.ytimg.com/vi/QxNe3k0b9EU/maxresdefault.jpg",
    "spotifyId": null,
    "reason": "4.5M views — emotional Oromo ballad.",
    "score": 66
  },
  {
    "id": "2",
    "ytId": "UlqLeuVHpEU",
    "views": 16618824,
    "likes": 132327,
    "comments": 11563,
    "publishedAt": "2026-04-16T11:56:16Z",
    "thumbUrl": "https://i.ytimg.com/vi/UlqLeuVHpEU/maxresdefault.jpg",
    "youtubeUrl": "https://www.youtube.com/watch?v=UlqLeuVHpEU",
    "title": "Shih Bibal (Back to 90s)",
    "artist": "Teddy Afro",
    "weekViews": 5569,
    "growthRate": 0.0003,
    "rank": 5,
    "prev": 5,
    "isNew": false,
    "isTrending": false,
    "score": 96,
    "country": "Ethiopia",
    "lang": "Amharic",
    "genre": "Afropop",
    "reason": "Shih Bibal holds strong at #3. 11M total views.",
    "spotifyId": "24HI7QnQdANExXzERYFG5X",
    "year": 2026
  },
  {
    "id": "5",
    "ytId": "DsH_LxBB4l8",
    "views": 13194134,
    "likes": 122153,
    "comments": 10035,
    "publishedAt": "2026-04-16T11:31:16Z",
    "thumbUrl": "https://i.ytimg.com/vi/DsH_LxBB4l8/maxresdefault.jpg",
    "youtubeUrl": "https://www.youtube.com/watch?v=DsH_LxBB4l8",
    "title": "Ze Tsedal",
    "artist": "Teddy Afro",
    "weekViews": 4452,
    "growthRate": 0.0003,
    "rank": 6,
    "prev": 17,
    "isNew": false,
    "isTrending": false,
    "score": 92,
    "country": "Ethiopia",
    "lang": "Amharic",
    "genre": "Afropop",
    "reason": "Ze Tsedal #6. 6.2M total.",
    "spotifyId": "3OgblJIfPnkkJnMZgg2jIi",
    "year": 2026
  },
  {
    "id": "1",
    "ytId": "ADc9JPeLYi4",
    "views": 28485061,
    "likes": 333462,
    "comments": 68944,
    "publishedAt": "2026-04-16T12:34:06Z",
    "thumbUrl": "https://i.ytimg.com/vi/ADc9JPeLYi4/maxresdefault.jpg",
    "youtubeUrl": "https://www.youtube.com/watch?v=ADc9JPeLYi4",
    "title": "Das Tal (Ansaw)",
    "artist": "Teddy Afro",
    "weekViews": 4406,
    "growthRate": 0.0002,
    "rank": 7,
    "prev": 14,
    "isNew": false,
    "isTrending": false,
    "score": 99,
    "country": "Ethiopia",
    "lang": "Amharic",
    "genre": "Afropop",
    "reason": "Das Tal hits 19M — confirmed via YouTube. #1 across Ethiopia & diaspora.",
    "spotifyId": "1UtV70tciiIMGk2b4l8TXv",
    "year": 2026
  },
  {
    "id": "11",
    "ytId": "pRHWe6Lz2mY",
    "views": 9011878,
    "likes": 89171,
    "comments": 6627,
    "publishedAt": "2026-04-16T11:52:06Z",
    "thumbUrl": "https://i.ytimg.com/vi/pRHWe6Lz2mY/maxresdefault.jpg",
    "youtubeUrl": "https://www.youtube.com/watch?v=pRHWe6Lz2mY",
    "title": "Tayegn",
    "artist": "Teddy Afro",
    "weekViews": 3548,
    "growthRate": 0.0004,
    "rank": 8,
    "prev": 21,
    "isNew": false,
    "isTrending": false,
    "score": 84,
    "country": "Ethiopia",
    "lang": "Amharic",
    "genre": "Afropop",
    "reason": "Tayegn #14.",
    "spotifyId": "6W9Io07rE9BOrDZQAWWjCq",
    "year": 2026
  },
  {
    "id": "3",
    "ytId": "nw443G62EQc",
    "views": 15566233,
    "likes": 130771,
    "comments": 14236,
    "publishedAt": "2026-04-16T12:16:21Z",
    "thumbUrl": "https://i.ytimg.com/vi/nw443G62EQc/maxresdefault.jpg",
    "youtubeUrl": "https://www.youtube.com/watch?v=nw443G62EQc",
    "title": "Sememene (GuReggae)",
    "artist": "Teddy Afro",
    "weekViews": 3453,
    "growthRate": 0.0002,
    "rank": 9,
    "prev": 15,
    "isNew": false,
    "isTrending": false,
    "score": 97,
    "country": "Ethiopia",
    "lang": "Amharic",
    "genre": "Afropop",
    "reason": "Sememene jumps to #2. 9.1M total — confirmed YouTube Music listing.",
    "spotifyId": "1Fb3ueLohCnOzUQE24gJGv",
    "year": 2026
  },
  {
    "id": "7",
    "ytId": "BQSgYf4lfMg",
    "views": 10848731,
    "likes": 122453,
    "comments": 13302,
    "publishedAt": "2026-04-16T11:16:16Z",
    "thumbUrl": "https://i.ytimg.com/vi/BQSgYf4lfMg/maxresdefault.jpg",
    "youtubeUrl": "https://www.youtube.com/watch?v=BQSgYf4lfMg",
    "title": "Merkeb",
    "artist": "Teddy Afro",
    "weekViews": 3188,
    "growthRate": 0.0003,
    "rank": 10,
    "prev": 18,
    "isNew": false,
    "isTrending": false,
    "score": 87,
    "country": "Ethiopia",
    "lang": "Amharic",
    "genre": "Afropop",
    "reason": "Merkeb #11.",
    "spotifyId": "1Fljm7P6ZUjMm9xVtF9NOf",
    "year": 2026
  },
  {
    "id": "8",
    "ytId": "IYf-RLJNMGU",
    "views": 9992089,
    "likes": 137963,
    "comments": 13459,
    "publishedAt": "2026-04-16T12:10:06Z",
    "thumbUrl": "https://i.ytimg.com/vi/IYf-RLJNMGU/maxresdefault.jpg",
    "youtubeUrl": "https://www.youtube.com/watch?v=IYf-RLJNMGU",
    "title": "Tsion Mushraye",
    "artist": "Teddy Afro",
    "weekViews": 2023,
    "growthRate": 0.0002,
    "rank": 11,
    "prev": 19,
    "isNew": false,
    "isTrending": false,
    "score": 86,
    "country": "Ethiopia",
    "lang": "Amharic",
    "genre": "Afropop",
    "reason": "Tsion Mushraye #12.",
    "spotifyId": "4YJOW9ikgOFaLB2TN7hHwN",
    "year": 2026
  },
  {
    "id": "9",
    "ytId": "FoBBYyvZCkc",
    "views": 8515244,
    "likes": 102065,
    "comments": 8131,
    "publishedAt": "2026-04-16T11:40:06Z",
    "thumbUrl": "https://i.ytimg.com/vi/FoBBYyvZCkc/maxresdefault.jpg",
    "youtubeUrl": "https://www.youtube.com/watch?v=FoBBYyvZCkc",
    "title": "Bilchita",
    "artist": "Teddy Afro",
    "weekViews": 1989,
    "growthRate": 0.0002,
    "rank": 12,
    "prev": 20,
    "isNew": false,
    "isTrending": false,
    "score": 85,
    "country": "Ethiopia",
    "lang": "Amharic",
    "genre": "Afropop",
    "reason": "Bilchita #13.",
    "spotifyId": "1oTSyBy9qYzgXdesGnjqIq",
    "year": 2026
  },
  {
    "id": "16",
    "ytId": "FvHyBLvGJl0",
    "views": 6609340,
    "likes": 72661,
    "comments": 5240,
    "publishedAt": "2026-04-16T12:20:17Z",
    "thumbUrl": "https://i.ytimg.com/vi/FvHyBLvGJl0/maxresdefault.jpg",
    "youtubeUrl": "https://www.youtube.com/watch?v=FvHyBLvGJl0",
    "title": "Tewedaj",
    "artist": "Teddy Afro",
    "weekViews": 1826,
    "growthRate": 0.0003,
    "rank": 13,
    "prev": 24,
    "isNew": false,
    "isTrending": false,
    "score": 88,
    "country": "Ethiopia",
    "lang": "Amharic",
    "genre": "Afropop",
    "reason": "Tewedaj #10. 3.8M — confirmed YouTube Music listing.",
    "spotifyId": "5sji1Zt2WRYLJXARQkqGWY",
    "year": 2026
  },
  {
    "id": "e2",
    "ytId": "e6vSKh9hiBU",
    "views": 32096423,
    "likes": 133557,
    "comments": 8956,
    "publishedAt": "2025-05-09T15:00:07Z",
    "thumbUrl": "https://i.ytimg.com/vi/e6vSKh9hiBU/maxresdefault.jpg",
    "youtubeUrl": "https://www.youtube.com/watch?v=e6vSKh9hiBU",
    "title": "Tewehade",
    "artist": "Mak Ezra",
    "weekViews": 1208,
    "growthRate": 0,
    "rank": 14,
    "prev": 30,
    "isNew": false,
    "isTrending": false,
    "score": 97,
    "country": "Ethiopia",
    "lang": "Tigrinya",
    "genre": "Tigrinya Pop",
    "reason": "30.6M views.",
    "spotifyId": "1cQrs9WCV7YSCn276gmOCJ",
    "year": 2025
  },
  {
    "id": "14",
    "ytId": "jvYGP-reKEI",
    "views": 6128615,
    "likes": 80831,
    "comments": 5854,
    "publishedAt": "2026-04-16T12:24:11Z",
    "thumbUrl": "https://i.ytimg.com/vi/jvYGP-reKEI/maxresdefault.jpg",
    "youtubeUrl": "https://www.youtube.com/watch?v=jvYGP-reKEI",
    "title": "Samnew",
    "artist": "Teddy Afro",
    "weekViews": 1098,
    "growthRate": 0.0002,
    "rank": 15,
    "prev": 23,
    "isNew": false,
    "isTrending": false,
    "score": 89,
    "country": "Ethiopia",
    "lang": "Amharic",
    "genre": "Afropop",
    "reason": "Samnew #9. 4.2M — confirmed YouTube Music listing.",
    "spotifyId": "4JuywWmfrQyc4sMdCKknzt",
    "year": 2026
  },
  {
    "id": "6",
    "ytId": "jaBZ9xXM2gU",
    "views": 8953265,
    "likes": 150769,
    "comments": 19701,
    "publishedAt": "2026-04-16T11:22:16Z",
    "thumbUrl": "https://i.ytimg.com/vi/jaBZ9xXM2gU/maxresdefault.jpg",
    "youtubeUrl": "https://www.youtube.com/watch?v=jaBZ9xXM2gU",
    "title": "Merema",
    "artist": "Teddy Afro",
    "weekViews": 958,
    "growthRate": 0.0001,
    "rank": 16,
    "prev": 6,
    "isNew": false,
    "isTrending": false,
    "score": 91,
    "country": "Ethiopia",
    "lang": "Amharic",
    "genre": "Afropop",
    "reason": "Merema #7. 7.1M total.",
    "spotifyId": "6DQVdhZPS7IfZRrX0prika",
    "year": 2026
  },
  {
    "id": "20",
    "ytId": "8EjcYircKvw",
    "views": 4785712,
    "likes": 67750,
    "comments": 3516,
    "publishedAt": "2026-04-11T15:00:38Z",
    "thumbUrl": "https://i.ytimg.com/vi/8EjcYircKvw/maxresdefault.jpg",
    "youtubeUrl": "https://www.youtube.com/watch?v=8EjcYircKvw",
    "title": "Digis New",
    "artist": "Yo Marios",
    "weekViews": 924,
    "growthRate": 0.0002,
    "rank": 17,
    "prev": 28,
    "isNew": false,
    "isTrending": false,
    "score": 78,
    "country": "Ethiopia",
    "lang": "Amharic",
    "genre": "Pop",
    "reason": "Digis New by Yo Marios #20.",
    "spotifyId": null,
    "year": 2026
  },
  {
    "id": "13",
    "ytId": "d1rAhwRJNyI",
    "views": 6127469,
    "likes": 79018,
    "comments": 6578,
    "publishedAt": "2026-04-16T12:05:06Z",
    "thumbUrl": "https://i.ytimg.com/vi/d1rAhwRJNyI/maxresdefault.jpg",
    "youtubeUrl": "https://www.youtube.com/watch?v=d1rAhwRJNyI",
    "title": "Tintago (Pintago)",
    "artist": "Teddy Afro",
    "weekViews": 891,
    "growthRate": 0.0001,
    "rank": 18,
    "prev": 22,
    "isNew": false,
    "isTrending": false,
    "score": 83,
    "country": "Ethiopia",
    "lang": "Amharic",
    "genre": "Afropop",
    "reason": "Tintago #15.",
    "spotifyId": "2pZzAJFxBFHCiF5k4gvFid",
    "year": 2026
  },
  {
    "id": "4",
    "ytId": "PA2aWF37Ljk",
    "views": 10454939,
    "likes": 221199,
    "comments": 30989,
    "publishedAt": "2026-04-16T11:00:24Z",
    "thumbUrl": "https://i.ytimg.com/vi/PA2aWF37Ljk/maxresdefault.jpg",
    "youtubeUrl": "https://www.youtube.com/watch?v=PA2aWF37Ljk",
    "title": "Jember",
    "artist": "Teddy Afro",
    "weekViews": 863,
    "growthRate": 0.0001,
    "rank": 19,
    "prev": 16,
    "isNew": false,
    "isTrending": false,
    "score": 95,
    "country": "Ethiopia",
    "lang": "Amharic",
    "genre": "Afropop",
    "reason": "Jember steady at #4. 1M views in 3 hours on release day.",
    "spotifyId": "1NB4UkzI7nwqjnEtKwoMey",
    "year": 2026
  },
  {
    "id": "24",
    "ytId": "RGW5nMfZpp4",
    "views": 22858939,
    "likes": 80110,
    "comments": 3564,
    "publishedAt": "2025-07-25T15:30:26Z",
    "thumbUrl": "https://i.ytimg.com/vi/RGW5nMfZpp4/maxresdefault.jpg",
    "youtubeUrl": "https://www.youtube.com/watch?v=RGW5nMfZpp4",
    "title": "Eyu Tsega",
    "artist": "Eyu Tsega",
    "weekViews": 776,
    "growthRate": 0,
    "rank": 20,
    "prev": 7,
    "isNew": false,
    "isTrending": false,
    "score": 74,
    "country": "Ethiopia",
    "lang": "Amharic",
    "genre": "Pop",
    "reason": "Eyu Tsega — 21.5M total.",
    "spotifyId": null,
    "year": 2025
  },
  {
    "id": "e1",
    "ytId": "oBgUwARHrCo",
    "views": 14971976,
    "likes": 63283,
    "comments": 4319,
    "publishedAt": "2025-09-09T14:00:07Z",
    "thumbUrl": "https://i.ytimg.com/vi/oBgUwARHrCo/maxresdefault.jpg",
    "youtubeUrl": "https://www.youtube.com/watch?v=oBgUwARHrCo",
    "title": "Shane",
    "artist": "Timnit Welday",
    "weekViews": 749,
    "growthRate": 0.0001,
    "rank": 21,
    "prev": 35,
    "isNew": false,
    "isTrending": false,
    "score": 98,
    "country": "Ethiopia",
    "lang": "Tigrinya",
    "genre": "Tigrinya Pop",
    "reason": "13.9M views.",
    "spotifyId": null,
    "year": 2025
  },
  {
    "id": "27",
    "ytId": "gliv_skuGL8",
    "views": 27395049,
    "likes": 82816,
    "comments": 5415,
    "publishedAt": "2015-06-04T09:59:05Z",
    "thumbUrl": "https://i.ytimg.com/vi/gliv_skuGL8/maxresdefault.jpg",
    "youtubeUrl": "https://www.youtube.com/watch?v=gliv_skuGL8",
    "title": "Maalan Jira",
    "artist": "Hachalu Hundessa",
    "weekViews": 716,
    "growthRate": 0,
    "rank": 22,
    "prev": 33,
    "isNew": false,
    "isTrending": false,
    "score": 70,
    "country": "Ethiopia",
    "lang": "Oromo",
    "genre": "Oromo Pop",
    "reason": "23M views — most iconic Oromo song.",
    "spotifyId": null,
    "year": 2020
  },
  {
    "id": "18",
    "ytId": "Mg0Wu49V8Bw",
    "views": 4895058,
    "likes": 89454,
    "comments": 6966,
    "publishedAt": "2026-04-16T11:46:06Z",
    "thumbUrl": "https://i.ytimg.com/vi/Mg0Wu49V8Bw/maxresdefault.jpg",
    "youtubeUrl": "https://www.youtube.com/watch?v=Mg0Wu49V8Bw",
    "title": "Bemeskotu",
    "artist": "Teddy Afro",
    "weekViews": 708,
    "growthRate": 0.0001,
    "rank": 23,
    "prev": 26,
    "isNew": false,
    "isTrending": false,
    "score": 80,
    "country": "Ethiopia",
    "lang": "Amharic",
    "genre": "Afropop",
    "reason": "Bemeskotu #18.",
    "spotifyId": "50dRGiAQRLJuLBhN369BtS",
    "year": 2026
  },
  {
    "id": "28",
    "ytId": "rV4iG4nn5Iw",
    "views": 17005618,
    "likes": 85674,
    "comments": 5177,
    "publishedAt": "2025-08-22T15:01:29Z",
    "thumbUrl": "https://i.ytimg.com/vi/rV4iG4nn5Iw/maxresdefault.jpg",
    "youtubeUrl": "https://www.youtube.com/watch?v=rV4iG4nn5Iw",
    "title": "Neger Neger",
    "artist": "Nati Ker",
    "weekViews": 695,
    "growthRate": 0,
    "rank": 24,
    "prev": 34,
    "isNew": false,
    "isTrending": false,
    "score": 69,
    "country": "Ethiopia",
    "lang": "Guragigna",
    "genre": "Gurage Pop",
    "reason": "15M views — viral Gurage hit.",
    "spotifyId": null,
    "year": 2022
  },
  {
    "id": "17",
    "ytId": "UHNizap0GX4",
    "views": 5850764,
    "likes": 113346,
    "comments": 9969,
    "publishedAt": "2026-04-16T11:11:06Z",
    "thumbUrl": "https://i.ytimg.com/vi/UHNizap0GX4/maxresdefault.jpg",
    "youtubeUrl": "https://www.youtube.com/watch?v=UHNizap0GX4",
    "title": "Sema Erase",
    "artist": "Teddy Afro",
    "weekViews": 686,
    "growthRate": 0.0001,
    "rank": 25,
    "prev": 25,
    "isNew": false,
    "isTrending": false,
    "score": 81,
    "country": "Ethiopia",
    "lang": "Amharic",
    "genre": "Afropop",
    "reason": "Sema Erase #17.",
    "spotifyId": "1Gi7sWaZd8OLKubbbxAliy",
    "year": 2026
  },
  {
    "id": "e3",
    "ytId": "jWSRjGB3JMU",
    "views": 20383973,
    "likes": 88660,
    "comments": 5968,
    "publishedAt": "2025-04-25T15:32:29Z",
    "thumbUrl": "https://i.ytimg.com/vi/jWSRjGB3JMU/maxresdefault.jpg",
    "youtubeUrl": "https://www.youtube.com/watch?v=jWSRjGB3JMU",
    "title": "Mizan",
    "artist": "Selamawit Yohannes",
    "weekViews": 637,
    "growthRate": 0,
    "rank": 26,
    "prev": 8,
    "isNew": false,
    "isTrending": false,
    "score": 95,
    "country": "Ethiopia",
    "lang": "Tigrinya",
    "genre": "Tigrinya Pop",
    "reason": "19.4M views.",
    "spotifyId": null,
    "year": 2025
  },
  {
    "id": "19",
    "ytId": "NbYJmTUy1jg",
    "views": 4055946,
    "likes": 67349,
    "comments": 5577,
    "publishedAt": "2026-04-16T12:01:16Z",
    "thumbUrl": "https://i.ytimg.com/vi/NbYJmTUy1jg/maxresdefault.jpg",
    "youtubeUrl": "https://www.youtube.com/watch?v=NbYJmTUy1jg",
    "title": "Yemaereg Tig",
    "artist": "Teddy Afro",
    "weekViews": 627,
    "growthRate": 0.0002,
    "rank": 27,
    "prev": 27,
    "isNew": false,
    "isTrending": false,
    "score": 79,
    "country": "Ethiopia",
    "lang": "Amharic",
    "genre": "Afropop",
    "reason": "Yemaereg Tig #19.",
    "spotifyId": "5vVAE0Wb6VPRe0hKpAoThV",
    "year": 2026
  },
  {
    "id": "12",
    "ytId": "oEIySELAmqU",
    "views": 5611037,
    "likes": 100363,
    "comments": 9049,
    "publishedAt": "2026-04-16T12:29:06Z",
    "thumbUrl": "https://i.ytimg.com/vi/oEIySELAmqU/maxresdefault.jpg",
    "youtubeUrl": "https://www.youtube.com/watch?v=oEIySELAmqU",
    "title": "Etorika",
    "artist": "Teddy Afro",
    "weekViews": 526,
    "growthRate": 0.0001,
    "rank": 28,
    "prev": 9,
    "isNew": false,
    "isTrending": false,
    "score": 90,
    "country": "Ethiopia",
    "lang": "Amharic",
    "genre": "Afropop",
    "reason": "Etorika title track #8. 4.4M — confirmed YouTube Music.",
    "spotifyId": "20H1kn9Bn7KYMiYhVlzKuK",
    "year": 2026
  },
  {
    "id": "15",
    "ytId": "sPYgRlfA-kc",
    "views": 5518694,
    "likes": 96666,
    "comments": 9544,
    "publishedAt": "2026-04-16T11:35:16Z",
    "thumbUrl": "https://i.ytimg.com/vi/sPYgRlfA-kc/maxresdefault.jpg",
    "youtubeUrl": "https://www.youtube.com/watch?v=sPYgRlfA-kc",
    "title": "Yeazo Emba",
    "artist": "Teddy Afro",
    "weekViews": 476,
    "growthRate": 0.0001,
    "rank": 29,
    "prev": 10,
    "isNew": false,
    "isTrending": false,
    "score": 82,
    "country": "Ethiopia",
    "lang": "Amharic",
    "genre": "Afropop",
    "reason": "Yeazo Emba #16.",
    "spotifyId": "0jvufzrp4kLIpTgmyN1n5f",
    "year": 2026
  },
  {
    "id": "32",
    "ytId": "jSgnlSaT_Ts",
    "views": 5719841,
    "likes": 55485,
    "comments": 5118,
    "publishedAt": "2025-09-30T14:52:06Z",
    "thumbUrl": "https://i.ytimg.com/vi/jSgnlSaT_Ts/maxresdefault.jpg",
    "youtubeUrl": "https://www.youtube.com/watch?v=jSgnlSaT_Ts",
    "title": "Yaa Shuurakoo",
    "artist": "Gelana Garomsa",
    "weekViews": 468,
    "growthRate": 0.0001,
    "rank": 30,
    "prev": 32,
    "isNew": false,
    "isTrending": false,
    "score": 65,
    "country": "Ethiopia",
    "lang": "Oromo",
    "genre": "Oromo Pop",
    "reason": "5M total views.",
    "spotifyId": null,
    "year": 2023
  },
  {
    "id": "21",
    "ytId": "naph6wDDooU",
    "views": 1247699,
    "likes": 20657,
    "comments": 941,
    "publishedAt": "2026-04-28T14:01:19Z",
    "thumbUrl": "https://i.ytimg.com/vi/naph6wDDooU/maxresdefault.jpg",
    "youtubeUrl": "https://www.youtube.com/watch?v=naph6wDDooU",
    "title": "Yelebe Sew",
    "artist": "Eden Aysheshem",
    "weekViews": 431,
    "growthRate": 0.0003,
    "rank": 31,
    "prev": 29,
    "isNew": false,
    "isTrending": false,
    "score": 77,
    "country": "Ethiopia",
    "lang": "Amharic",
    "genre": "Pop",
    "reason": "Yelebe Sew — Eden Aysheshem, gaining traction.",
    "spotifyId": null,
    "year": 2026
  },
  {
    "id": "23",
    "ytId": "JxjGMGJmP8U",
    "views": 1597226,
    "likes": 22419,
    "comments": 913,
    "publishedAt": "2026-04-12T15:45:02Z",
    "thumbUrl": "https://i.ytimg.com/vi/JxjGMGJmP8U/maxresdefault.jpg",
    "youtubeUrl": "https://www.youtube.com/watch?v=JxjGMGJmP8U",
    "title": "Maru Negn ke Dessie",
    "artist": "JA",
    "weekViews": 426,
    "growthRate": 0.0003,
    "rank": 32,
    "prev": 31,
    "isNew": false,
    "isTrending": false,
    "score": 76,
    "country": "Ethiopia",
    "lang": "Amharic",
    "genre": "Pop",
    "reason": "Maru Negn ke Dessie — JA climbing fast.",
    "spotifyId": null,
    "year": 2026
  },
  {
    "id": "e10",
    "ytId": "o4JUximUsCM",
    "views": 2645590,
    "likes": 12859,
    "comments": 835,
    "publishedAt": "2025-11-28T15:01:31Z",
    "thumbUrl": "https://i.ytimg.com/vi/o4JUximUsCM/maxresdefault.jpg",
    "youtubeUrl": "https://www.youtube.com/watch?v=o4JUximUsCM",
    "title": "Gudam",
    "artist": "Temesgen Teklay (Siktit)",
    "weekViews": 372,
    "growthRate": 0.0001,
    "rank": 33,
    "prev": 40,
    "isNew": false,
    "isTrending": false,
    "score": 82,
    "country": "Eritrea",
    "lang": "Tigrinya",
    "genre": "Tigrinya Pop",
    "reason": "+101K this week.",
    "spotifyId": null,
    "year": 2025
  },
  {
    "id": "e5",
    "ytId": "jvxWsiK49nM",
    "views": 4497377,
    "likes": 18057,
    "comments": 1322,
    "publishedAt": "2025-10-25T13:01:34Z",
    "thumbUrl": "https://i.ytimg.com/vi/jvxWsiK49nM/maxresdefault.jpg",
    "youtubeUrl": "https://www.youtube.com/watch?v=jvxWsiK49nM",
    "title": "Atinye",
    "artist": "Embza Aligaz",
    "weekViews": 331,
    "growthRate": 0.0001,
    "rank": 34,
    "prev": 37,
    "isNew": false,
    "isTrending": false,
    "score": 90,
    "country": "Eritrea",
    "lang": "Tigrinya",
    "genre": "Tigrinya Pop",
    "reason": "+134K this week.",
    "spotifyId": null,
    "year": 2025
  },
  {
    "id": "e4",
    "ytId": "wnK1O310CZI",
    "views": 15543303,
    "likes": 48963,
    "comments": 2622,
    "publishedAt": "2025-01-10T15:01:21Z",
    "thumbUrl": "https://i.ytimg.com/vi/wnK1O310CZI/maxresdefault.jpg",
    "youtubeUrl": "https://www.youtube.com/watch?v=wnK1O310CZI",
    "title": "Niskila",
    "artist": "Amanuel Yemane",
    "weekViews": 260,
    "growthRate": 0,
    "rank": 35,
    "prev": 36,
    "isNew": false,
    "isTrending": false,
    "score": 92,
    "country": "Ethiopia",
    "lang": "Tigrinya",
    "genre": "Tigrinya Pop",
    "reason": "14.8M views.",
    "spotifyId": "2AlalWAdrCPEXxLrBeEd6U",
    "year": 2025
  },
  {
    "id": "e7",
    "ytId": "yegG7qClGy0",
    "views": 5614381,
    "likes": 27775,
    "comments": 1514,
    "publishedAt": "2025-05-23T15:17:19Z",
    "thumbUrl": "https://i.ytimg.com/vi/yegG7qClGy0/maxresdefault.jpg",
    "youtubeUrl": "https://www.youtube.com/watch?v=yegG7qClGy0",
    "title": "Elakani",
    "artist": "Rahel Haile",
    "weekViews": 256,
    "growthRate": 0,
    "rank": 36,
    "prev": 11,
    "isNew": false,
    "isTrending": false,
    "score": 86,
    "country": "Eritrea",
    "lang": "Tigrinya",
    "genre": "Tigrinya Pop",
    "reason": "5M views.",
    "spotifyId": null,
    "year": 2025
  },
  {
    "id": "e12",
    "ytId": "YybkSxcgvIQ",
    "views": 12277175,
    "likes": 60922,
    "comments": 2913,
    "publishedAt": "2025-01-24T15:00:43Z",
    "thumbUrl": "https://i.ytimg.com/vi/YybkSxcgvIQ/maxresdefault.jpg",
    "youtubeUrl": "https://www.youtube.com/watch?v=YybkSxcgvIQ",
    "title": "Tayti",
    "artist": "Yared Netsanet",
    "weekViews": 252,
    "growthRate": 0,
    "rank": 37,
    "prev": 41,
    "isNew": false,
    "isTrending": false,
    "score": 78,
    "country": "Ethiopia",
    "lang": "Tigrinya",
    "genre": "Tigrinya Pop",
    "reason": "3.1M views.",
    "spotifyId": null,
    "year": 2024
  },
  {
    "id": "e9",
    "ytId": "lvAoHssg6qQ",
    "views": 7553961,
    "likes": 57581,
    "comments": 5119,
    "publishedAt": "2025-09-13T12:52:49Z",
    "thumbUrl": "https://i.ytimg.com/vi/lvAoHssg6qQ/maxresdefault.jpg",
    "youtubeUrl": "https://www.youtube.com/watch?v=lvAoHssg6qQ",
    "title": "Zara",
    "artist": "Solomon Yikunoamlak",
    "weekViews": 222,
    "growthRate": 0,
    "rank": 38,
    "prev": 39,
    "isNew": false,
    "isTrending": false,
    "score": 84,
    "country": "Eritrea",
    "lang": "Tigrinya",
    "genre": "Tigrinya Pop",
    "reason": "7.1M views.",
    "spotifyId": null,
    "year": 2025
  },
  {
    "id": "e8",
    "ytId": "HOADb_H4buk",
    "views": 7339063,
    "likes": 47824,
    "comments": 4457,
    "publishedAt": "2025-06-13T14:00:11Z",
    "thumbUrl": "https://i.ytimg.com/vi/HOADb_H4buk/maxresdefault.jpg",
    "youtubeUrl": "https://www.youtube.com/watch?v=HOADb_H4buk",
    "title": "Maeger",
    "artist": "Nguse Abadi",
    "weekViews": 209,
    "growthRate": 0,
    "rank": 39,
    "prev": 38,
    "isNew": false,
    "isTrending": false,
    "score": 85,
    "country": "Eritrea",
    "lang": "Tigrinya",
    "genre": "Tigrinya Pop",
    "reason": "6.7M views.",
    "spotifyId": null,
    "year": 2025
  },
  {
    "id": "e6",
    "ytId": "Zs-r2C86fis",
    "views": 4010144,
    "likes": 36845,
    "comments": 2446,
    "publishedAt": "2025-11-28T15:00:07Z",
    "thumbUrl": "https://i.ytimg.com/vi/Zs-r2C86fis/maxresdefault.jpg",
    "youtubeUrl": "https://www.youtube.com/watch?v=Zs-r2C86fis",
    "title": "Akayda",
    "artist": "Merkeb Bonitua",
    "weekViews": 186,
    "growthRate": 0,
    "rank": 40,
    "prev": 13,
    "isNew": false,
    "isTrending": false,
    "score": 88,
    "country": "Eritrea",
    "lang": "Tigrinya",
    "genre": "Tigrinya Pop",
    "reason": "3.3M views.",
    "spotifyId": null,
    "year": 2025
  },
  {
    "id": "26",
    "ytId": "P9KzCEdCuV4",
    "views": 3068120,
    "likes": 83236,
    "comments": 54637,
    "publishedAt": "2026-04-17T22:05:42Z",
    "thumbUrl": "https://i.ytimg.com/vi/P9KzCEdCuV4/maxresdefault.jpg",
    "youtubeUrl": "https://www.youtube.com/watch?v=P9KzCEdCuV4",
    "title": "Galmee Seenaa",
    "artist": "Gelana Garomsa ft Yosan Getahun",
    "weekViews": 128,
    "growthRate": 0,
    "rank": 41,
    "prev": 12,
    "isNew": false,
    "isTrending": false,
    "score": 71,
    "country": "Ethiopia",
    "lang": "Oromo",
    "genre": "Oromo Pop",
    "reason": "2.4M views debut week. Already in charts.",
    "spotifyId": null,
    "year": 2026
  }
];
