const SONGS = [
  {
  "songs": [
    {
      "id": "1",
      "rank": 1,
      "prev": 1,
      "isNew": false,
      "title": "Das Tal (Ansaw)",
      "artist": "Teddy Afro",
      "country": "Ethiopia",
      "lang": "Amharic",
      "genre": "Afropop",
      "views": 19000000,
      "weekViews": 4800000,
      "year": 2026,
      "ytId": "ADc9JPeLYi4",
      "thumbUrl": "https://i.ytimg.com/vi/ADc9JPeLYi4/maxresdefault.jpg",
      "spotifyId": "1UtV70tciiIMGk2b4l8TXv",
      "reason": "Das Tal hits 19M — confirmed via YouTube. #1 across Ethiopia & diaspora.",
      "score": 99
    },
    {
      "id": "2",
      "rank": 3,
      "prev": 2,
      "isNew": false,
      "title": "Shih Bibal (Back to 90s)",
      "artist": "Teddy Afro",
      "country": "Ethiopia",
      "lang": "Amharic",
      "genre": "Afropop",
      "views": 11000000,
      "weekViews": 2800000,
      "year": 2026,
      "ytId": "UlqLeuVHpEU",
      "thumbUrl": "https://i.ytimg.com/vi/UlqLeuVHpEU/maxresdefault.jpg",
      "spotifyId": "24HI7QnQdANExXzERYFG5X",
      "reason": "Shih Bibal holds strong at #3. 11M total views.",
      "score": 96
    },
    {
      "id": "3",
      "rank": 2,
      "prev": 3,
      "isNew": false,
      "title": "Sememene (GuReggae)",
      "artist": "Teddy Afro",
      "country": "Ethiopia",
      "lang": "Amharic",
      "genre": "Afropop",
      "views": 9100000,
      "weekViews": 3200000,
      "year": 2026,
      "ytId": "nw443G62EQc",
      "thumbUrl": "https://i.ytimg.com/vi/nw443G62EQc/maxresdefault.jpg",
      "spotifyId": "1Fb3ueLohCnOzUQE24gJGv",
      "reason": "Sememene jumps to #2. 9.1M total — confirmed YouTube Music listing.",
      "score": 97
    },
    {
      "id": "4",
      "rank": 4,
      "prev": 4,
      "isNew": false,
      "title": "Jember",
      "artist": "Teddy Afro",
      "country": "Ethiopia",
      "lang": "Amharic",
      "genre": "Afropop",
      "views": 9500000,
      "weekViews": 2500000,
      "year": 2026,
      "ytId": "PA2aWF37Ljk",
      "thumbUrl": "https://i.ytimg.com/vi/PA2aWF37Ljk/maxresdefault.jpg",
      "spotifyId": "1NB4UkzI7nwqjnEtKwoMey",
      "reason": "Jember steady at #4. 1M views in 3 hours on release day.",
      "score": 95
    },
    {
      "id": "5",
      "rank": 6,
      "prev": 5,
      "isNew": false,
      "title": "Ze Tsedal",
      "artist": "Teddy Afro",
      "country": "Ethiopia",
      "lang": "Amharic",
      "genre": "Afropop",
      "views": 6200000,
      "weekViews": 1900000,
      "year": 2026,
      "ytId": "DsH_LxBB4l8",
      "thumbUrl": "https://i.ytimg.com/vi/DsH_LxBB4l8/maxresdefault.jpg",
      "spotifyId": "3OgblJIfPnkkJnMZgg2jIi",
      "reason": "Ze Tsedal #6. 6.2M total.",
      "score": 92
    },
    {
      "id": "6",
      "rank": 7,
      "prev": 6,
      "isNew": false,
      "title": "Merema",
      "artist": "Teddy Afro",
      "country": "Ethiopia",
      "lang": "Amharic",
      "genre": "Afropop",
      "views": 7100000,
      "weekViews": 1800000,
      "year": 2026,
      "ytId": "jaBZ9xXM2gU",
      "thumbUrl": "https://i.ytimg.com/vi/jaBZ9xXM2gU/maxresdefault.jpg",
      "spotifyId": "6DQVdhZPS7IfZRrX0prika",
      "reason": "Merema #7. 7.1M total.",
      "score": 91
    },
    {
      "id": "7",
      "rank": 11,
      "prev": 7,
      "isNew": false,
      "title": "Merkeb",
      "artist": "Teddy Afro",
      "country": "Ethiopia",
      "lang": "Amharic",
      "genre": "Afropop",
      "views": 5600000,
      "weekViews": 1450000,
      "year": 2026,
      "ytId": "BQSgYf4lfMg",
      "thumbUrl": "https://i.ytimg.com/vi/BQSgYf4lfMg/maxresdefault.jpg",
      "spotifyId": "1Fljm7P6ZUjMm9xVtF9NOf",
      "reason": "Merkeb #11.",
      "score": 87
    },
    {
      "id": "8",
      "rank": 12,
      "prev": 8,
      "isNew": false,
      "title": "Tsion Mushraye",
      "artist": "Teddy Afro",
      "country": "Ethiopia",
      "lang": "Amharic",
      "genre": "Afropop",
      "views": 5900000,
      "weekViews": 1400000,
      "year": 2026,
      "ytId": "IYf-RLJNMGU",
      "thumbUrl": "https://i.ytimg.com/vi/IYf-RLJNMGU/maxresdefault.jpg",
      "spotifyId": "4YJOW9ikgOFaLB2TN7hHwN",
      "reason": "Tsion Mushraye #12.",
      "score": 86
    },
    {
      "id": "9",
      "rank": 13,
      "prev": 9,
      "isNew": false,
      "title": "Bilchita",
      "artist": "Teddy Afro",
      "country": "Ethiopia",
      "lang": "Amharic",
      "genre": "Afropop",
      "views": 5000000,
      "weekViews": 1350000,
      "year": 2026,
      "ytId": "FoBBYyvZCkc",
      "thumbUrl": "https://i.ytimg.com/vi/FoBBYyvZCkc/maxresdefault.jpg",
      "spotifyId": "1oTSyBy9qYzgXdesGnjqIq",
      "reason": "Bilchita #13.",
      "score": 85
    },
    {
      "id": "10",
      "rank": 5,
      "prev": 10,
      "isNew": false,
      "title": "Galmee Seenaa",
      "artist": "Gelana Garomsa ft Yosan Getahun",
      "country": "Ethiopia",
      "lang": "Oromo",
      "genre": "Oromo Pop",
      "views": 3500000,
      "weekViews": 3500000,
      "year": 2026,
      "ytId": "P9KzCEdCuV4",
      "thumbUrl": "https://i.ytimg.com/vi/P9KzCEdCuV4/maxresdefault.jpg",
      "spotifyId": null,
      "reason": "Galmee Seenaa surges to #5. 1.1M in 23hrs, now 3.5M total — direct Etorika response track.",
      "score": 94
    },
    {
      "id": "11",
      "rank": 14,
      "prev": 11,
      "isNew": false,
      "title": "Tayegn",
      "artist": "Teddy Afro",
      "country": "Ethiopia",
      "lang": "Amharic",
      "genre": "Afropop",
      "views": 4100000,
      "weekViews": 1300000,
      "year": 2026,
      "ytId": "pRHWe6Lz2mY",
      "thumbUrl": "https://i.ytimg.com/vi/pRHWe6Lz2mY/maxresdefault.jpg",
      "spotifyId": "6W9Io07rE9BOrDZQAWWjCq",
      "reason": "Tayegn #14.",
      "score": 84
    },
    {
      "id": "12",
      "rank": 8,
      "prev": 12,
      "isNew": false,
      "title": "Etorika",
      "artist": "Teddy Afro",
      "country": "Ethiopia",
      "lang": "Amharic",
      "genre": "Afropop",
      "views": 4400000,
      "weekViews": 1600000,
      "year": 2026,
      "ytId": "oEIySELAmqU",
      "thumbUrl": "https://i.ytimg.com/vi/oEIySELAmqU/maxresdefault.jpg",
      "spotifyId": "20H1kn9Bn7KYMiYhVlzKuK",
      "reason": "Etorika title track #8. 4.4M — confirmed YouTube Music.",
      "score": 90
    },
    {
      "id": "13",
      "rank": 15,
      "prev": 13,
      "isNew": false,
      "title": "Tintago (Pintago)",
      "artist": "Teddy Afro",
      "country": "Ethiopia",
      "lang": "Amharic",
      "genre": "Afropop",
      "views": 4000000,
      "weekViews": 1250000,
      "year": 2026,
      "ytId": "d1rAhwRJNyI",
      "thumbUrl": "https://i.ytimg.com/vi/d1rAhwRJNyI/maxresdefault.jpg",
      "spotifyId": "2pZzAJFxBFHCiF5k4gvFid",
      "reason": "Tintago #15.",
      "score": 83
    },
    {
      "id": "14",
      "rank": 9,
      "prev": 14,
      "isNew": false,
      "title": "Samnew",
      "artist": "Teddy Afro",
      "country": "Ethiopia",
      "lang": "Amharic",
      "genre": "Afropop",
      "views": 4200000,
      "weekViews": 1550000,
      "year": 2026,
      "ytId": "jvYGP-reKEI",
      "thumbUrl": "https://i.ytimg.com/vi/jvYGP-reKEI/maxresdefault.jpg",
      "spotifyId": "4JuywWmfrQyc4sMdCKknzt",
      "reason": "Samnew #9. 4.2M — confirmed YouTube Music listing.",
      "score": 89
    },
    {
      "id": "15",
      "rank": 16,
      "prev": 15,
      "isNew": false,
      "title": "Yeazo Emba",
      "artist": "Teddy Afro",
      "country": "Ethiopia",
      "lang": "Amharic",
      "genre": "Afropop",
      "views": 4000000,
      "weekViews": 1100000,
      "year": 2026,
      "ytId": "sPYgRlfA-kc",
      "thumbUrl": "https://i.ytimg.com/vi/sPYgRlfA-kc/maxresdefault.jpg",
      "spotifyId": "0jvufzrp4kLIpTgmyN1n5f",
      "reason": "Yeazo Emba #16.",
      "score": 82
    },
    {
      "id": "16",
      "rank": 10,
      "prev": 16,
      "isNew": false,
      "title": "Tewedaj",
      "artist": "Teddy Afro",
      "country": "Ethiopia",
      "lang": "Amharic",
      "genre": "Afropop",
      "views": 3800000,
      "weekViews": 1500000,
      "year": 2026,
      "ytId": "FvHyBLvGJl0",
      "thumbUrl": "https://i.ytimg.com/vi/FvHyBLvGJl0/maxresdefault.jpg",
      "spotifyId": "5sji1Zt2WRYLJXARQkqGWY",
      "reason": "Tewedaj #10. 3.8M — confirmed YouTube Music listing.",
      "score": 88
    },
    {
      "id": "17",
      "rank": 17,
      "prev": 17,
      "isNew": false,
      "title": "Sema Erase",
      "artist": "Teddy Afro",
      "country": "Ethiopia",
      "lang": "Amharic",
      "genre": "Afropop",
      "views": 4200000,
      "weekViews": 1050000,
      "year": 2026,
      "ytId": "UHNizap0GX4",
      "thumbUrl": "https://i.ytimg.com/vi/UHNizap0GX4/maxresdefault.jpg",
      "spotifyId": "1Gi7sWaZd8OLKubbbxAliy",
      "reason": "Sema Erase #17.",
      "score": 81
    },
    {
      "id": "18",
      "rank": 18,
      "prev": 18,
      "isNew": false,
      "title": "Bemeskotu",
      "artist": "Teddy Afro",
      "country": "Ethiopia",
      "lang": "Amharic",
      "genre": "Afropop",
      "views": 3400000,
      "weekViews": 980000,
      "year": 2026,
      "ytId": "Mg0Wu49V8Bw",
      "thumbUrl": "https://i.ytimg.com/vi/Mg0Wu49V8Bw/maxresdefault.jpg",
      "spotifyId": "50dRGiAQRLJuLBhN369BtS",
      "reason": "Bemeskotu #18.",
      "score": 80
    },
    {
      "id": "19",
      "rank": 19,
      "prev": 19,
      "isNew": false,
      "title": "Yemaereg Tig",
      "artist": "Teddy Afro",
      "country": "Ethiopia",
      "lang": "Amharic",
      "genre": "Afropop",
      "views": 2700000,
      "weekViews": 880000,
      "year": 2026,
      "ytId": "NbYJmTUy1jg",
      "thumbUrl": "https://i.ytimg.com/vi/NbYJmTUy1jg/maxresdefault.jpg",
      "spotifyId": "5vVAE0Wb6VPRe0hKpAoThV",
      "reason": "Yemaereg Tig #19.",
      "score": 79
    },
    {
      "id": "20",
      "rank": 20,
      "prev": 20,
      "isNew": false,
      "title": "Digis New",
      "artist": "Yo Marios",
      "country": "Ethiopia",
      "lang": "Amharic",
      "genre": "Pop",
      "views": 3100000,
      "weekViews": 850000,
      "year": 2026,
      "ytId": "8EjcYircKvw",
      "thumbUrl": "https://i.ytimg.com/vi/8EjcYircKvw/maxresdefault.jpg",
      "spotifyId": null,
      "reason": "Digis New by Yo Marios #20.",
      "score": 78
    },
    {
      "id": "21",
      "rank": 21,
      "prev": 21,
      "isNew": false,
      "title": "Yelebe Sew",
      "artist": "Eden Aysheshem",
      "country": "Ethiopia",
      "lang": "Amharic",
      "genre": "Pop",
      "views": 620000,
      "weekViews": 280000,
      "year": 2026,
      "ytId": "naph6wDDooU",
      "thumbUrl": "https://i.ytimg.com/vi/naph6wDDooU/maxresdefault.jpg",
      "spotifyId": null,
      "reason": "Yelebe Sew — Eden Aysheshem, gaining traction.",
      "score": 77
    },
    {
      "id": "22",
      "rank": 23,
      "prev": 22,
      "isNew": false,
      "title": "Tewehade",
      "artist": "Mak Ezra",
      "country": "Ethiopia",
      "lang": "Tigrinya",
      "genre": "Tigrinya Pop",
      "views": 30800000,
      "weekViews": 200000,
      "year": 2025,
      "ytId": "e6vSKh9hiBU",
      "thumbUrl": "https://i.ytimg.com/vi/e6vSKh9hiBU/maxresdefault.jpg",
      "spotifyId": "1cQrs9WCV7YSCn276gmOCJ",
      "reason": "Tewehade — Mak Ezra. 30.8M total.",
      "score": 75
    },
    {
      "id": "23",
      "rank": 22,
      "prev": 23,
      "isNew": false,
      "title": "Maru Negn ke Dessie",
      "artist": "JA",
      "country": "Ethiopia",
      "lang": "Amharic",
      "genre": "Pop",
      "views": 900000,
      "weekViews": 400000,
      "year": 2026,
      "ytId": "JxjGMGJmP8U",
      "thumbUrl": "https://i.ytimg.com/vi/JxjGMGJmP8U/maxresdefault.jpg",
      "spotifyId": null,
      "reason": "Maru Negn ke Dessie — JA climbing fast.",
      "score": 76
    },
    {
      "id": "24",
      "rank": 24,
      "prev": 24,
      "isNew": false,
      "title": "Eyu Tsega",
      "artist": "Eyu Tsega",
      "country": "Ethiopia",
      "lang": "Amharic",
      "genre": "Pop",
      "views": 21500000,
      "weekViews": 180000,
      "year": 2025,
      "ytId": "RGW5nMfZpp4",
      "thumbUrl": "https://i.ytimg.com/vi/RGW5nMfZpp4/maxresdefault.jpg",
      "spotifyId": null,
      "reason": "Eyu Tsega — 21.5M total.",
      "score": 74
    },
    {
      "id": "25",
      "rank": 25,
      "prev": 25,
      "isNew": false,
      "title": "Yaa Shuurakoo",
      "artist": "Gelana Garomsa",
      "country": "Ethiopia",
      "lang": "Oromo",
      "genre": "Oromo Pop",
      "views": 5200000,
      "weekViews": 150000,
      "year": 2025,
      "ytId": "jSgnlSaT_Ts",
      "thumbUrl": "https://i.ytimg.com/vi/jSgnlSaT_Ts/maxresdefault.jpg",
      "spotifyId": null,
      "reason": "Yaa Shuurakoo — Gelana Garomsa. 5.2M.",
      "score": 73
    },
    {
      "id": "26",
      "rank": 26,
      "prev": 26,
      "isNew": false,
      "title": "Galmee Seenaa",
      "artist": "Gelana Garomsa ft Yosan Getahun",
      "country": "Ethiopia",
      "lang": "Oromo",
      "genre": "Oromo Pop",
      "views": 2423103,
      "weekViews": 95000,
      "year": 2026,
      "ytId": "P9KzCEdCuV4",
      "thumbUrl": "https://i.ytimg.com/vi/P9KzCEdCuV4/maxresdefault.jpg",
      "spotifyId": null,
      "reason": "2.4M views debut week. Already in charts.",
      "score": 71
    },
    {
      "id": "27",
      "rank": 27,
      "prev": 27,
      "isNew": false,
      "title": "Maalan Jira",
      "artist": "Hachalu Hundessa",
      "country": "Ethiopia",
      "lang": "Oromo",
      "genre": "Oromo Pop",
      "views": 23000000,
      "weekViews": 60000,
      "year": 2020,
      "ytId": "gliv_skuGL8",
      "thumbUrl": "https://i.ytimg.com/vi/gliv_skuGL8/maxresdefault.jpg",
      "spotifyId": null,
      "reason": "23M views — most iconic Oromo song.",
      "score": 70
    },
    {
      "id": "28",
      "rank": 28,
      "prev": 28,
      "isNew": false,
      "title": "Neger Neger",
      "artist": "Nati Ker",
      "country": "Ethiopia",
      "lang": "Guragigna",
      "genre": "Gurage Pop",
      "views": 15279868,
      "weekViews": 55000,
      "year": 2022,
      "ytId": "rV4iG4nn5Iw",
      "thumbUrl": "https://i.ytimg.com/vi/rV4iG4nn5Iw/maxresdefault.jpg",
      "spotifyId": null,
      "reason": "15M views — viral Gurage hit.",
      "score": 69
    },
    {
      "id": "29",
      "rank": 29,
      "prev": 29,
      "isNew": false,
      "title": "Minnow Nesh",
      "artist": "Hachalu Hundessa",
      "country": "Ethiopia",
      "lang": "Oromo",
      "genre": "Oromo Pop",
      "views": 8200000,
      "weekViews": 42000,
      "year": 2021,
      "ytId": "2ixjSHqHqpU",
      "thumbUrl": "https://i.ytimg.com/vi/2ixjSHqHqpU/maxresdefault.jpg",
      "spotifyId": null,
      "reason": "8.2M views — beloved Oromo anthem.",
      "score": 68
    },
    {
      "id": "30",
      "rank": 30,
      "prev": 30,
      "isNew": false,
      "title": "Sabbata",
      "artist": "Dawit Tsige",
      "country": "Ethiopia",
      "lang": "Oromo",
      "genre": "Oromo Pop",
      "views": 6100000,
      "weekViews": 38000,
      "year": 2022,
      "ytId": "Gk6ZkJoFBnE",
      "thumbUrl": "https://i.ytimg.com/vi/Gk6ZkJoFBnE/maxresdefault.jpg",
      "spotifyId": null,
      "reason": "6.1M views — top Oromo pop track.",
      "score": 67
    },
    {
      "id": "31",
      "rank": 31,
      "prev": 31,
      "isNew": false,
      "title": "Siifan Jira",
      "artist": "Caalaa Bultumee",
      "country": "Ethiopia",
      "lang": "Oromo",
      "genre": "Oromo Pop",
      "views": 4500000,
      "weekViews": 30000,
      "year": 2023,
      "ytId": "QxNe3k0b9EU",
      "thumbUrl": "https://i.ytimg.com/vi/QxNe3k0b9EU/maxresdefault.jpg",
      "spotifyId": null,
      "reason": "4.5M views — emotional Oromo ballad.",
      "score": 66
    },
    {
      "id": "32",
      "rank": 32,
      "prev": 32,
      "isNew": false,
      "title": "Yaa Shuurakoo",
      "artist": "Gelana Garomsa",
      "country": "Ethiopia",
      "lang": "Oromo",
      "genre": "Oromo Pop",
      "views": 5065000,
      "weekViews": 28000,
      "year": 2023,
      "ytId": "jSgnlSaT_Ts",
      "thumbUrl": "https://i.ytimg.com/vi/jSgnlSaT_Ts/maxresdefault.jpg",
      "spotifyId": null,
      "reason": "5M total views.",
      "score": 65
    },
    {
      "id": "e1",
      "rank": 1,
      "prev": 1,
      "isNew": false,
      "title": "Shane",
      "artist": "Timnit Welday",
      "country": "Eritrea",
      "lang": "Tigrinya",
      "genre": "Tigrinya Pop",
      "views": 13916615,
      "weekViews": 233418,
      "year": 2025,
      "ytId": "oBgUwARHrCo",
      "thumbUrl": "https://i.ytimg.com/vi/oBgUwARHrCo/maxresdefault.jpg",
      "spotifyId": null,
      "reason": "13.9M views.",
      "score": 98
    },
    {
      "id": "e2",
      "rank": 2,
      "prev": 2,
      "isNew": false,
      "title": "Tewehade",
      "artist": "Mak Ezra",
      "country": "Eritrea",
      "lang": "Tigrinya",
      "genre": "Tigrinya Pop",
      "views": 30600000,
      "weekViews": 370831,
      "year": 2025,
      "ytId": "e6vSKh9hiBU",
      "thumbUrl": "https://i.ytimg.com/vi/e6vSKh9hiBU/maxresdefault.jpg",
      "spotifyId": "1cQrs9WCV7YSCn276gmOCJ",
      "reason": "30.6M views.",
      "score": 97
    },
    {
      "id": "e3",
      "rank": 3,
      "prev": 3,
      "isNew": false,
      "title": "Mizan",
      "artist": "Selamawit Yohannes",
      "country": "Eritrea",
      "lang": "Tigrinya",
      "genre": "Tigrinya Pop",
      "views": 19422844,
      "weekViews": 215269,
      "year": 2025,
      "ytId": "jWSRjGB3JMU",
      "thumbUrl": "https://i.ytimg.com/vi/jWSRjGB3JMU/maxresdefault.jpg",
      "spotifyId": null,
      "reason": "19.4M views.",
      "score": 95
    },
    {
      "id": "e4",
      "rank": 4,
      "prev": 4,
      "isNew": false,
      "title": "Niskila",
      "artist": "Amanuel Yemane",
      "country": "Eritrea",
      "lang": "Tigrinya",
      "genre": "Tigrinya Pop",
      "views": 14816314,
      "weekViews": 40239,
      "year": 2025,
      "ytId": "wnK1O310CZI",
      "thumbUrl": "https://i.ytimg.com/vi/wnK1O310CZI/maxresdefault.jpg",
      "spotifyId": "2AlalWAdrCPEXxLrBeEd6U",
      "reason": "14.8M views.",
      "score": 92
    },
    {
      "id": "e5",
      "rank": 5,
      "prev": 5,
      "isNew": false,
      "title": "Atinye",
      "artist": "Embza Aligaz",
      "country": "Eritrea",
      "lang": "Tigrinya",
      "genre": "Tigrinya Pop",
      "views": 3868670,
      "weekViews": 134699,
      "year": 2025,
      "ytId": "jvxWsiK49nM",
      "thumbUrl": "https://i.ytimg.com/vi/jvxWsiK49nM/maxresdefault.jpg",
      "spotifyId": null,
      "reason": "+134K this week.",
      "score": 90
    },
    {
      "id": "e6",
      "rank": 6,
      "prev": 6,
      "isNew": false,
      "title": "Akayda",
      "artist": "Merkeb Bonitua",
      "country": "Eritrea",
      "lang": "Tigrinya",
      "genre": "Tigrinya Pop",
      "views": 3367915,
      "weekViews": 51979,
      "year": 2025,
      "ytId": "Zs-r2C86fis",
      "thumbUrl": "https://i.ytimg.com/vi/Zs-r2C86fis/maxresdefault.jpg",
      "spotifyId": null,
      "reason": "3.3M views.",
      "score": 88
    },
    {
      "id": "e7",
      "rank": 7,
      "prev": 7,
      "isNew": false,
      "title": "Elakani",
      "artist": "Rahel Haile",
      "country": "Eritrea",
      "lang": "Tigrinya",
      "genre": "Tigrinya Pop",
      "views": 5052079,
      "weekViews": 39939,
      "year": 2025,
      "ytId": "yegG7qClGy0",
      "thumbUrl": "https://i.ytimg.com/vi/yegG7qClGy0/maxresdefault.jpg",
      "spotifyId": null,
      "reason": "5M views.",
      "score": 86
    },
    {
      "id": "e8",
      "rank": 8,
      "prev": 8,
      "isNew": false,
      "title": "Maeger",
      "artist": "Nguse Abadi",
      "country": "Eritrea",
      "lang": "Tigrinya",
      "genre": "Tigrinya Pop",
      "views": 6768512,
      "weekViews": 37685,
      "year": 2025,
      "ytId": "HOADb_H4buk",
      "thumbUrl": "https://i.ytimg.com/vi/HOADb_H4buk/maxresdefault.jpg",
      "spotifyId": null,
      "reason": "6.7M views.",
      "score": 85
    },
    {
      "id": "e9",
      "rank": 9,
      "prev": 9,
      "isNew": false,
      "title": "Zara",
      "artist": "Solomon Yikunoamlak",
      "country": "Eritrea",
      "lang": "Tigrinya",
      "genre": "Tigrinya Pop",
      "views": 7120303,
      "weekViews": 96729,
      "year": 2025,
      "ytId": "lvAoHssg6qQ",
      "thumbUrl": "https://i.ytimg.com/vi/lvAoHssg6qQ/maxresdefault.jpg",
      "spotifyId": null,
      "reason": "7.1M views.",
      "score": 84
    },
    {
      "id": "e10",
      "rank": 10,
      "prev": 10,
      "isNew": false,
      "title": "Gudam",
      "artist": "Temesgen Teklay (Siktit)",
      "country": "Eritrea",
      "lang": "Tigrinya",
      "genre": "Tigrinya Pop",
      "views": 2134485,
      "weekViews": 101393,
      "year": 2025,
      "ytId": "o4JUximUsCM",
      "thumbUrl": "https://i.ytimg.com/vi/o4JUximUsCM/maxresdefault.jpg",
      "spotifyId": null,
      "reason": "+101K this week.",
      "score": 82
    },
    {
      "id": "e11",
      "rank": 11,
      "prev": 11,
      "isNew": false,
      "title": "Libi Zbele",
      "artist": "Helen Meles",
      "country": "Eritrea",
      "lang": "Tigrinya",
      "genre": "Tigrinya Pop",
      "views": 4200000,
      "weekViews": 32000,
      "year": 2024,
      "ytId": "Q0wH8GVbRfY",
      "thumbUrl": "https://i.ytimg.com/vi/Q0wH8GVbRfY/maxresdefault.jpg",
      "spotifyId": null,
      "reason": "4.2M views.",
      "score": 80
    },
    {
      "id": "e12",
      "rank": 12,
      "prev": 12,
      "isNew": false,
      "title": "Tayti",
      "artist": "Yared Netsanet",
      "country": "Eritrea",
      "lang": "Tigrinya",
      "genre": "Tigrinya Pop",
      "views": 3100000,
      "weekViews": 28000,
      "year": 2024,
      "ytId": "YybkSxcgvIQ",
      "thumbUrl": "https://i.ytimg.com/vi/YybkSxcgvIQ/maxresdefault.jpg",
      "spotifyId": null,
      "reason": "3.1M views.",
      "score": 78
    }
  ]
}
];
