const SONGS = [
  {
    "id": "2",
    "ytId": "UlqLeuVHpEU",
    "views": 20978477,
    "likes": 142360,
    "comments": 11946,
    "publishedAt": "2026-04-16T11:56:16Z",
    "thumbUrl": "https://i.ytimg.com/vi/UlqLeuVHpEU/maxresdefault.jpg",
    "youtubeUrl": "https://www.youtube.com/watch?v=UlqLeuVHpEU",
    "title": "Shih Bibal (Back to 90s)",
    "artist": "Teddy Afro",
    "weekViews": 4359653,
    "growthRate": 0.2623,
    "rank": 1,
    "prev": 16,
    "isNew": false,
    "isTrending": false,
    "score": 96,
    "country": "Ethiopia",
    "lang": "Amharic",
    "genre": "Afropop",
    "reason": "Shih Bibal holds strong at #3. 11M total views.",
    "spotifyId": "24HI7QnQdANExXzERYFG5X",
    "year": 2026
  },
  {
    "id": "1",
    "ytId": "ADc9JPeLYi4",
    "views": 31396133,
    "likes": 340536,
    "comments": 69699,
    "publishedAt": "2026-04-16T12:34:06Z",
    "thumbUrl": "https://i.ytimg.com/vi/ADc9JPeLYi4/maxresdefault.jpg",
    "youtubeUrl": "https://www.youtube.com/watch?v=ADc9JPeLYi4",
    "title": "Das Tal (Ansaw)",
    "artist": "Teddy Afro",
    "weekViews": 2911072,
    "growthRate": 0.1022,
    "rank": 2,
    "prev": 15,
    "isNew": false,
    "isTrending": false,
    "score": 99,
    "country": "Ethiopia",
    "lang": "Amharic",
    "genre": "Afropop",
    "reason": "Das Tal hits 19M — confirmed via YouTube. #1 across Ethiopia & diaspora.",
    "spotifyId": "1UtV70tciiIMGk2b4l8TXv",
    "year": 2026
  },
  {
    "id": "5",
    "ytId": "DsH_LxBB4l8",
    "views": 16064456,
    "likes": 127195,
    "comments": 10283,
    "publishedAt": "2026-04-16T11:31:16Z",
    "thumbUrl": "https://i.ytimg.com/vi/DsH_LxBB4l8/maxresdefault.jpg",
    "youtubeUrl": "https://www.youtube.com/watch?v=DsH_LxBB4l8",
    "title": "Ze Tsedal",
    "artist": "Teddy Afro",
    "weekViews": 2870322,
    "growthRate": 0.2175,
    "rank": 3,
    "prev": 18,
    "isNew": false,
    "isTrending": false,
    "score": 92,
    "country": "Ethiopia",
    "lang": "Amharic",
    "genre": "Afropop",
    "reason": "Ze Tsedal #6. 6.2M total.",
    "spotifyId": "3OgblJIfPnkkJnMZgg2jIi",
    "year": 2026
  },
  {
    "id": "3",
    "ytId": "nw443G62EQc",
    "views": 18090349,
    "likes": 135549,
    "comments": 14456,
    "publishedAt": "2026-04-16T12:16:21Z",
    "thumbUrl": "https://i.ytimg.com/vi/nw443G62EQc/maxresdefault.jpg",
    "youtubeUrl": "https://www.youtube.com/watch?v=nw443G62EQc",
    "title": "Sememene (GuReggae)",
    "artist": "Teddy Afro",
    "weekViews": 2523248,
    "growthRate": 0.1621,
    "rank": 4,
    "prev": 3,
    "isNew": false,
    "isTrending": false,
    "score": 97,
    "country": "Ethiopia",
    "lang": "Amharic",
    "genre": "Afropop",
    "reason": "Sememene climbs to #3 — Teddy Afro holding strong.",
    "spotifyId": "1Fb3ueLohCnOzUQE24gJGv",
    "year": 2026
  },
  {
    "id": "11",
    "ytId": "pRHWe6Lz2mY",
    "views": 11083065,
    "likes": 92233,
    "comments": 6808,
    "publishedAt": "2026-04-16T11:52:06Z",
    "thumbUrl": "https://i.ytimg.com/vi/pRHWe6Lz2mY/maxresdefault.jpg",
    "youtubeUrl": "https://www.youtube.com/watch?v=pRHWe6Lz2mY",
    "title": "Tayegn",
    "artist": "Teddy Afro",
    "weekViews": 2071187,
    "growthRate": 0.2298,
    "rank": 5,
    "prev": 23,
    "isNew": false,
    "isTrending": false,
    "score": 84,
    "country": "Ethiopia",
    "lang": "Amharic",
    "genre": "Afropop",
    "reason": "Tayegn #14.",
    "spotifyId": "6W9Io07rE9BOrDZQAWWjCq",
    "year": 2026
  },
  {
    "id": "7",
    "ytId": "BQSgYf4lfMg",
    "views": 12689248,
    "likes": 125720,
    "comments": 13498,
    "publishedAt": "2026-04-16T11:16:16Z",
    "thumbUrl": "https://i.ytimg.com/vi/BQSgYf4lfMg/maxresdefault.jpg",
    "youtubeUrl": "https://www.youtube.com/watch?v=BQSgYf4lfMg",
    "title": "Merkeb",
    "artist": "Teddy Afro",
    "weekViews": 1840517,
    "growthRate": 0.1697,
    "rank": 6,
    "prev": 20,
    "isNew": false,
    "isTrending": false,
    "score": 87,
    "country": "Ethiopia",
    "lang": "Amharic",
    "genre": "Afropop",
    "reason": "Merkeb #11.",
    "spotifyId": "1Fljm7P6ZUjMm9xVtF9NOf",
    "year": 2026
  },
  {
    "id": "8",
    "ytId": "IYf-RLJNMGU",
    "views": 11328601,
    "likes": 140076,
    "comments": 13575,
    "publishedAt": "2026-04-16T12:10:06Z",
    "thumbUrl": "https://i.ytimg.com/vi/IYf-RLJNMGU/maxresdefault.jpg",
    "youtubeUrl": "https://www.youtube.com/watch?v=IYf-RLJNMGU",
    "title": "Tsion Mushraye",
    "artist": "Teddy Afro",
    "weekViews": 1336032,
    "growthRate": 0.1337,
    "rank": 7,
    "prev": 4,
    "isNew": false,
    "isTrending": false,
    "score": 86,
    "country": "Ethiopia",
    "lang": "Amharic",
    "genre": "Afropop",
    "reason": "Tsion Mushraye up to #4.",
    "spotifyId": "4YJOW9ikgOFaLB2TN7hHwN",
    "year": 2026
  },
  {
    "id": "9",
    "ytId": "FoBBYyvZCkc",
    "views": 9732306,
    "likes": 104520,
    "comments": 8234,
    "publishedAt": "2026-04-16T11:40:06Z",
    "thumbUrl": "https://i.ytimg.com/vi/FoBBYyvZCkc/maxresdefault.jpg",
    "youtubeUrl": "https://www.youtube.com/watch?v=FoBBYyvZCkc",
    "title": "Bilchita",
    "artist": "Teddy Afro",
    "weekViews": 1217062,
    "growthRate": 0.1429,
    "rank": 8,
    "prev": 21,
    "isNew": false,
    "isTrending": false,
    "score": 85,
    "country": "Ethiopia",
    "lang": "Amharic",
    "genre": "Afropop",
    "reason": "Bilchita #13.",
    "spotifyId": "1oTSyBy9qYzgXdesGnjqIq",
    "year": 2026
  },
  {
    "id": "e2",
    "ytId": "e6vSKh9hiBU",
    "views": 33133018,
    "likes": 135429,
    "comments": 9032,
    "publishedAt": "2025-05-09T15:00:07Z",
    "thumbUrl": "https://i.ytimg.com/vi/e6vSKh9hiBU/maxresdefault.jpg",
    "youtubeUrl": "https://www.youtube.com/watch?v=e6vSKh9hiBU",
    "title": "Tewehade",
    "artist": "Mak Ezra",
    "weekViews": 1036595,
    "growthRate": 0.0323,
    "rank": 9,
    "prev": 29,
    "isNew": false,
    "isTrending": false,
    "score": 97,
    "country": "Ethiopia",
    "lang": "Tigrinya",
    "genre": "Tigrinya Pop",
    "reason": "30.6M views.",
    "spotifyId": "1cQrs9WCV7YSCn276gmOCJ",
    "year": 2025
  },
  {
    "id": "16",
    "ytId": "FvHyBLvGJl0",
    "views": 7635033,
    "likes": 73923,
    "comments": 5289,
    "publishedAt": "2026-04-16T12:20:17Z",
    "thumbUrl": "https://i.ytimg.com/vi/FvHyBLvGJl0/maxresdefault.jpg",
    "youtubeUrl": "https://www.youtube.com/watch?v=FvHyBLvGJl0",
    "title": "Tewedaj",
    "artist": "Teddy Afro",
    "weekViews": 1025693,
    "growthRate": 0.1552,
    "rank": 10,
    "prev": 26,
    "isNew": false,
    "isTrending": false,
    "score": 88,
    "country": "Ethiopia",
    "lang": "Amharic",
    "genre": "Afropop",
    "reason": "Tewedaj #10. 3.8M — confirmed YouTube Music listing.",
    "spotifyId": "5sji1Zt2WRYLJXARQkqGWY",
    "year": 2026
  },
  {
    "id": "24",
    "ytId": "RGW5nMfZpp4",
    "views": 23724077,
    "likes": 81903,
    "comments": 3637,
    "publishedAt": "2025-07-25T15:30:26Z",
    "thumbUrl": "https://i.ytimg.com/vi/RGW5nMfZpp4/maxresdefault.jpg",
    "youtubeUrl": "https://www.youtube.com/watch?v=RGW5nMfZpp4",
    "title": "Eyu Tsega",
    "artist": "Eyu Tsega",
    "weekViews": 865138,
    "growthRate": 0.0378,
    "rank": 11,
    "prev": 31,
    "isNew": false,
    "isTrending": false,
    "score": 74,
    "country": "Ethiopia",
    "lang": "Amharic",
    "genre": "Pop",
    "reason": "Eyu Tsega — 21.5M total.",
    "spotifyId": null,
    "year": 2025
  },
  {
    "id": "20",
    "ytId": "8EjcYircKvw",
    "views": 5601651,
    "likes": 72135,
    "comments": 3629,
    "publishedAt": "2026-04-11T15:00:38Z",
    "thumbUrl": "https://i.ytimg.com/vi/8EjcYircKvw/maxresdefault.jpg",
    "youtubeUrl": "https://www.youtube.com/watch?v=8EjcYircKvw",
    "title": "Digis New",
    "artist": "Yo Marios",
    "weekViews": 815939,
    "growthRate": 0.1705,
    "rank": 12,
    "prev": 1,
    "isNew": false,
    "isTrending": false,
    "score": 78,
    "country": "Ethiopia",
    "lang": "Amharic",
    "genre": "Pop",
    "reason": "Digis New surges to #1 — Yo Marios viral this week.",
    "spotifyId": null,
    "year": 2026
  },
  {
    "id": "14",
    "ytId": "jvYGP-reKEI",
    "views": 6859125,
    "likes": 81887,
    "comments": 5894,
    "publishedAt": "2026-04-16T12:24:11Z",
    "thumbUrl": "https://i.ytimg.com/vi/jvYGP-reKEI/maxresdefault.jpg",
    "youtubeUrl": "https://www.youtube.com/watch?v=jvYGP-reKEI",
    "title": "Samnew",
    "artist": "Teddy Afro",
    "weekViews": 730271,
    "growthRate": 0.1192,
    "rank": 13,
    "prev": 5,
    "isNew": false,
    "isTrending": false,
    "score": 89,
    "country": "Ethiopia",
    "lang": "Amharic",
    "genre": "Afropop",
    "reason": "Samnew at #5 — 6.1M views and growing.",
    "spotifyId": "4JuywWmfrQyc4sMdCKknzt",
    "year": 2026
  },
  {
    "id": "e1",
    "ytId": "oBgUwARHrCo",
    "views": 15631656,
    "likes": 64367,
    "comments": 4372,
    "publishedAt": "2025-09-09T14:00:07Z",
    "thumbUrl": "https://i.ytimg.com/vi/oBgUwARHrCo/maxresdefault.jpg",
    "youtubeUrl": "https://www.youtube.com/watch?v=oBgUwARHrCo",
    "title": "Shane",
    "artist": "Timnit Welday",
    "weekViews": 659680,
    "growthRate": 0.0441,
    "rank": 14,
    "prev": 35,
    "isNew": false,
    "isTrending": false,
    "score": 98,
    "country": "Ethiopia",
    "lang": "Tigrinya",
    "genre": "Tigrinya Pop",
    "reason": "13.9M views.",
    "spotifyId": null,
    "year": 2025
  },
  {
    "id": "6",
    "ytId": "jaBZ9xXM2gU",
    "views": 9607234,
    "likes": 151980,
    "comments": 19771,
    "publishedAt": "2026-04-16T11:22:16Z",
    "thumbUrl": "https://i.ytimg.com/vi/jaBZ9xXM2gU/maxresdefault.jpg",
    "youtubeUrl": "https://www.youtube.com/watch?v=jaBZ9xXM2gU",
    "title": "Merema",
    "artist": "Teddy Afro",
    "weekViews": 653969,
    "growthRate": 0.073,
    "rank": 15,
    "prev": 19,
    "isNew": false,
    "isTrending": false,
    "score": 91,
    "country": "Ethiopia",
    "lang": "Amharic",
    "genre": "Afropop",
    "reason": "Merema #7. 7.1M total.",
    "spotifyId": "6DQVdhZPS7IfZRrX0prika",
    "year": 2026
  },
  {
    "id": "e3",
    "ytId": "jWSRjGB3JMU",
    "views": 21013991,
    "likes": 89995,
    "comments": 6004,
    "publishedAt": "2025-04-25T15:32:29Z",
    "thumbUrl": "https://i.ytimg.com/vi/jWSRjGB3JMU/maxresdefault.jpg",
    "youtubeUrl": "https://www.youtube.com/watch?v=jWSRjGB3JMU",
    "title": "Mizan",
    "artist": "Selamawit Yohannes",
    "weekViews": 630018,
    "growthRate": 0.0309,
    "rank": 16,
    "prev": 36,
    "isNew": false,
    "isTrending": false,
    "score": 95,
    "country": "Ethiopia",
    "lang": "Tigrinya",
    "genre": "Tigrinya Pop",
    "reason": "19.4M views.",
    "spotifyId": null,
    "year": 2025
  },
  {
    "id": "28",
    "ytId": "rV4iG4nn5Iw",
    "views": 17629961,
    "likes": 87141,
    "comments": 5222,
    "publishedAt": "2025-08-22T15:01:29Z",
    "thumbUrl": "https://i.ytimg.com/vi/rV4iG4nn5Iw/maxresdefault.jpg",
    "youtubeUrl": "https://www.youtube.com/watch?v=rV4iG4nn5Iw",
    "title": "Neger Neger",
    "artist": "Nati Ker",
    "weekViews": 624343,
    "growthRate": 0.0367,
    "rank": 17,
    "prev": 34,
    "isNew": false,
    "isTrending": false,
    "score": 69,
    "country": "Ethiopia",
    "lang": "Guragigna",
    "genre": "Gurage Pop",
    "reason": "15M views — viral Gurage hit.",
    "spotifyId": null,
    "year": 2022
  },
  {
    "id": "27",
    "ytId": "gliv_skuGL8",
    "views": 28003976,
    "likes": 84403,
    "comments": 5489,
    "publishedAt": "2015-06-04T09:59:05Z",
    "thumbUrl": "https://i.ytimg.com/vi/gliv_skuGL8/maxresdefault.jpg",
    "youtubeUrl": "https://www.youtube.com/watch?v=gliv_skuGL8",
    "title": "Maalan Jira",
    "artist": "Hachalu Hundessa",
    "weekViews": 608927,
    "growthRate": 0.0222,
    "rank": 18,
    "prev": 33,
    "isNew": false,
    "isTrending": false,
    "score": 70,
    "country": "Ethiopia",
    "lang": "Oromo",
    "genre": "Oromo Pop",
    "reason": "23M views — most iconic Oromo song.",
    "spotifyId": null,
    "year": 2020
  },
  {
    "id": "13",
    "ytId": "d1rAhwRJNyI",
    "views": 6704451,
    "likes": 79796,
    "comments": 6627,
    "publishedAt": "2026-04-16T12:05:06Z",
    "thumbUrl": "https://i.ytimg.com/vi/d1rAhwRJNyI/maxresdefault.jpg",
    "youtubeUrl": "https://www.youtube.com/watch?v=d1rAhwRJNyI",
    "title": "Tintago (Pintago)",
    "artist": "Teddy Afro",
    "weekViews": 576838,
    "growthRate": 0.0941,
    "rank": 19,
    "prev": 6,
    "isNew": false,
    "isTrending": false,
    "score": 83,
    "country": "Ethiopia",
    "lang": "Amharic",
    "genre": "Afropop",
    "reason": "Tintago (Pintago) climbs to #6.",
    "spotifyId": "2pZzAJFxBFHCiF5k4gvFid",
    "year": 2026
  },
  {
    "id": "4",
    "ytId": "PA2aWF37Ljk",
    "views": 11011880,
    "likes": 222231,
    "comments": 31059,
    "publishedAt": "2026-04-16T11:00:24Z",
    "thumbUrl": "https://i.ytimg.com/vi/PA2aWF37Ljk/maxresdefault.jpg",
    "youtubeUrl": "https://www.youtube.com/watch?v=PA2aWF37Ljk",
    "title": "Jember",
    "artist": "Teddy Afro",
    "weekViews": 556941,
    "growthRate": 0.0533,
    "rank": 20,
    "prev": 17,
    "isNew": false,
    "isTrending": false,
    "score": 95,
    "country": "Ethiopia",
    "lang": "Amharic",
    "genre": "Afropop",
    "reason": "Jember steady at #4. 1M views in 3 hours on release day.",
    "spotifyId": "1NB4UkzI7nwqjnEtKwoMey",
    "year": 2026
  },
  {
    "id": "17",
    "ytId": "UHNizap0GX4",
    "views": 6299124,
    "likes": 113982,
    "comments": 9996,
    "publishedAt": "2026-04-16T11:11:06Z",
    "thumbUrl": "https://i.ytimg.com/vi/UHNizap0GX4/maxresdefault.jpg",
    "youtubeUrl": "https://www.youtube.com/watch?v=UHNizap0GX4",
    "title": "Sema Erase",
    "artist": "Teddy Afro",
    "weekViews": 448250,
    "growthRate": 0.0766,
    "rank": 21,
    "prev": 7,
    "isNew": false,
    "isTrending": false,
    "score": 81,
    "country": "Ethiopia",
    "lang": "Amharic",
    "genre": "Afropop",
    "reason": "Sema Erase up to #7.",
    "spotifyId": "1Gi7sWaZd8OLKubbbxAliy",
    "year": 2026
  },
  {
    "id": "18",
    "ytId": "Mg0Wu49V8Bw",
    "views": 5320402,
    "likes": 90279,
    "comments": 7039,
    "publishedAt": "2026-04-16T11:46:06Z",
    "thumbUrl": "https://i.ytimg.com/vi/Mg0Wu49V8Bw/maxresdefault.jpg",
    "youtubeUrl": "https://www.youtube.com/watch?v=Mg0Wu49V8Bw",
    "title": "Bemeskotu",
    "artist": "Teddy Afro",
    "weekViews": 425344,
    "growthRate": 0.0869,
    "rank": 22,
    "prev": 27,
    "isNew": false,
    "isTrending": false,
    "score": 80,
    "country": "Ethiopia",
    "lang": "Amharic",
    "genre": "Afropop",
    "reason": "Bemeskotu #18.",
    "spotifyId": "50dRGiAQRLJuLBhN369BtS",
    "year": 2026
  },
  {
    "id": "15",
    "ytId": "sPYgRlfA-kc",
    "views": 5916732,
    "likes": 97399,
    "comments": 9619,
    "publishedAt": "2026-04-16T11:35:16Z",
    "thumbUrl": "https://i.ytimg.com/vi/sPYgRlfA-kc/maxresdefault.jpg",
    "youtubeUrl": "https://www.youtube.com/watch?v=sPYgRlfA-kc",
    "title": "Yeazo Emba",
    "artist": "Teddy Afro",
    "weekViews": 398038,
    "growthRate": 0.0721,
    "rank": 23,
    "prev": 25,
    "isNew": false,
    "isTrending": false,
    "score": 82,
    "country": "Ethiopia",
    "lang": "Amharic",
    "genre": "Afropop",
    "reason": "Yeazo Emba #16.",
    "spotifyId": "0jvufzrp4kLIpTgmyN1n5f",
    "year": 2026
  },
  {
    "id": "19",
    "ytId": "NbYJmTUy1jg",
    "views": 4423635,
    "likes": 67917,
    "comments": 5603,
    "publishedAt": "2026-04-16T12:01:16Z",
    "thumbUrl": "https://i.ytimg.com/vi/NbYJmTUy1jg/maxresdefault.jpg",
    "youtubeUrl": "https://www.youtube.com/watch?v=NbYJmTUy1jg",
    "title": "Yemaereg Tig",
    "artist": "Teddy Afro",
    "weekViews": 367689,
    "growthRate": 0.0907,
    "rank": 24,
    "prev": 28,
    "isNew": false,
    "isTrending": false,
    "score": 79,
    "country": "Ethiopia",
    "lang": "Amharic",
    "genre": "Afropop",
    "reason": "Yemaereg Tig #19.",
    "spotifyId": "5vVAE0Wb6VPRe0hKpAoThV",
    "year": 2026
  },
  {
    "id": "12",
    "ytId": "oEIySELAmqU",
    "views": 5951487,
    "likes": 101060,
    "comments": 9086,
    "publishedAt": "2026-04-16T12:29:06Z",
    "thumbUrl": "https://i.ytimg.com/vi/oEIySELAmqU/maxresdefault.jpg",
    "youtubeUrl": "https://www.youtube.com/watch?v=oEIySELAmqU",
    "title": "Etorika",
    "artist": "Teddy Afro",
    "weekViews": 340450,
    "growthRate": 0.0607,
    "rank": 25,
    "prev": 24,
    "isNew": false,
    "isTrending": false,
    "score": 90,
    "country": "Ethiopia",
    "lang": "Amharic",
    "genre": "Afropop",
    "reason": "Etorika title track #8. 4.4M — confirmed YouTube Music.",
    "spotifyId": "20H1kn9Bn7KYMiYhVlzKuK",
    "year": 2026
  },
  {
    "id": "23",
    "ytId": "JxjGMGJmP8U",
    "views": 1915105,
    "likes": 23537,
    "comments": 922,
    "publishedAt": "2026-04-12T15:45:02Z",
    "thumbUrl": "https://i.ytimg.com/vi/JxjGMGJmP8U/maxresdefault.jpg",
    "youtubeUrl": "https://www.youtube.com/watch?v=JxjGMGJmP8U",
    "title": "Maru Negn ke Dessie",
    "artist": "JA",
    "weekViews": 317879,
    "growthRate": 0.199,
    "rank": 26,
    "prev": 30,
    "isNew": false,
    "isTrending": false,
    "score": 76,
    "country": "Ethiopia",
    "lang": "Amharic",
    "genre": "Pop",
    "reason": "Maru Negn ke Dessie — JA climbing fast.",
    "spotifyId": null,
    "year": 2026
  },
  {
    "id": "e5",
    "ytId": "jvxWsiK49nM",
    "views": 4814848,
    "likes": 18535,
    "comments": 1342,
    "publishedAt": "2025-10-25T13:01:34Z",
    "thumbUrl": "https://i.ytimg.com/vi/jvxWsiK49nM/maxresdefault.jpg",
    "youtubeUrl": "https://www.youtube.com/watch?v=jvxWsiK49nM",
    "title": "Atinye",
    "artist": "Embza Aligaz",
    "weekViews": 317393,
    "growthRate": 0.0706,
    "rank": 27,
    "prev": 8,
    "isNew": false,
    "isTrending": false,
    "score": 90,
    "country": "Eritrea",
    "lang": "Tigrinya",
    "genre": "Tigrinya Pop",
    "reason": "Atinye at #8 — top Eritrean entry this week.",
    "spotifyId": null,
    "year": 2025
  },
  {
    "id": "e10",
    "ytId": "o4JUximUsCM",
    "views": 2949798,
    "likes": 13727,
    "comments": 875,
    "publishedAt": "2025-11-28T15:01:31Z",
    "thumbUrl": "https://i.ytimg.com/vi/o4JUximUsCM/maxresdefault.jpg",
    "youtubeUrl": "https://www.youtube.com/watch?v=o4JUximUsCM",
    "title": "Gudam",
    "artist": "Temesgen Teklay (Siktit)",
    "weekViews": 304208,
    "growthRate": 0.115,
    "rank": 28,
    "prev": 41,
    "isNew": false,
    "isTrending": false,
    "score": 82,
    "country": "Eritrea",
    "lang": "Tigrinya",
    "genre": "Tigrinya Pop",
    "reason": "+101K this week.",
    "spotifyId": null,
    "year": 2025
  },
  {
    "id": "32",
    "ytId": "jSgnlSaT_Ts",
    "views": 6013960,
    "likes": 56387,
    "comments": 5140,
    "publishedAt": "2025-09-30T14:52:06Z",
    "thumbUrl": "https://i.ytimg.com/vi/jSgnlSaT_Ts/maxresdefault.jpg",
    "youtubeUrl": "https://www.youtube.com/watch?v=jSgnlSaT_Ts",
    "title": "Yaa Shuurakoo",
    "artist": "Gelana Garomsa",
    "weekViews": 294119,
    "growthRate": 0.0514,
    "rank": 29,
    "prev": 32,
    "isNew": false,
    "isTrending": false,
    "score": 65,
    "country": "Ethiopia",
    "lang": "Oromo",
    "genre": "Oromo Pop",
    "reason": "5M total views.",
    "spotifyId": null,
    "year": 2023
  },
  {
    "id": "21",
    "ytId": "naph6wDDooU",
    "views": 1540968,
    "likes": 21894,
    "comments": 1010,
    "publishedAt": "2026-04-28T14:01:19Z",
    "thumbUrl": "https://i.ytimg.com/vi/naph6wDDooU/maxresdefault.jpg",
    "youtubeUrl": "https://www.youtube.com/watch?v=naph6wDDooU",
    "title": "Yelebe Sew",
    "artist": "Eden Aysheshem",
    "weekViews": 293199,
    "growthRate": 0.235,
    "rank": 30,
    "prev": 9,
    "isNew": false,
    "isTrending": false,
    "score": 77,
    "country": "Ethiopia",
    "lang": "Amharic",
    "genre": "Pop",
    "reason": "Yelebe Sew climbs to #9 — Eden Aysheshem gaining traction.",
    "spotifyId": null,
    "year": 2026
  },
  {
    "id": "e9",
    "ytId": "lvAoHssg6qQ",
    "views": 7784891,
    "likes": 58001,
    "comments": 5146,
    "publishedAt": "2025-09-13T12:52:49Z",
    "thumbUrl": "https://i.ytimg.com/vi/lvAoHssg6qQ/maxresdefault.jpg",
    "youtubeUrl": "https://www.youtube.com/watch?v=lvAoHssg6qQ",
    "title": "Zara",
    "artist": "Solomon Yikunoamlak",
    "weekViews": 230863,
    "growthRate": 0.0306,
    "rank": 31,
    "prev": 10,
    "isNew": false,
    "isTrending": false,
    "score": 84,
    "country": "Eritrea",
    "lang": "Tigrinya",
    "genre": "Tigrinya Pop",
    "reason": "Zara enters the top 10 at #10.",
    "spotifyId": null,
    "year": 2025
  },
  {
    "id": "e7",
    "ytId": "yegG7qClGy0",
    "views": 5829331,
    "likes": 28127,
    "comments": 1525,
    "publishedAt": "2025-05-23T15:17:19Z",
    "thumbUrl": "https://i.ytimg.com/vi/yegG7qClGy0/maxresdefault.jpg",
    "youtubeUrl": "https://www.youtube.com/watch?v=yegG7qClGy0",
    "title": "Elakani",
    "artist": "Rahel Haile",
    "weekViews": 214950,
    "growthRate": 0.0383,
    "rank": 32,
    "prev": 39,
    "isNew": false,
    "isTrending": false,
    "score": 86,
    "country": "Eritrea",
    "lang": "Tigrinya",
    "genre": "Tigrinya Pop",
    "reason": "5M views.",
    "spotifyId": null,
    "year": 2025
  },
  {
    "id": "e12",
    "ytId": "YybkSxcgvIQ",
    "views": 12488749,
    "likes": 61480,
    "comments": 2920,
    "publishedAt": "2025-01-24T15:00:43Z",
    "thumbUrl": "https://i.ytimg.com/vi/YybkSxcgvIQ/maxresdefault.jpg",
    "youtubeUrl": "https://www.youtube.com/watch?v=YybkSxcgvIQ",
    "title": "Tayti",
    "artist": "Yared Netsanet",
    "weekViews": 211574,
    "growthRate": 0.0172,
    "rank": 33,
    "prev": 42,
    "isNew": false,
    "isTrending": false,
    "score": 78,
    "country": "Ethiopia",
    "lang": "Tigrinya",
    "genre": "Tigrinya Pop",
    "reason": "3.1M views.",
    "spotifyId": null,
    "year": 2024
  },
  {
    "id": "e6",
    "ytId": "Zs-r2C86fis",
    "views": 4204743,
    "likes": 37345,
    "comments": 2460,
    "publishedAt": "2025-11-28T15:00:07Z",
    "thumbUrl": "https://i.ytimg.com/vi/Zs-r2C86fis/maxresdefault.jpg",
    "youtubeUrl": "https://www.youtube.com/watch?v=Zs-r2C86fis",
    "title": "Akayda",
    "artist": "Merkeb Bonitua",
    "weekViews": 194599,
    "growthRate": 0.0485,
    "rank": 34,
    "prev": 38,
    "isNew": false,
    "isTrending": false,
    "score": 88,
    "country": "Eritrea",
    "lang": "Tigrinya",
    "genre": "Tigrinya Pop",
    "reason": "3.3M views.",
    "spotifyId": null,
    "year": 2025
  },
  {
    "id": "e4",
    "ytId": "wnK1O310CZI",
    "views": 15724364,
    "likes": 49232,
    "comments": 2628,
    "publishedAt": "2025-01-10T15:01:21Z",
    "thumbUrl": "https://i.ytimg.com/vi/wnK1O310CZI/maxresdefault.jpg",
    "youtubeUrl": "https://www.youtube.com/watch?v=wnK1O310CZI",
    "title": "Niskila",
    "artist": "Amanuel Yemane",
    "weekViews": 181061,
    "growthRate": 0.0116,
    "rank": 35,
    "prev": 37,
    "isNew": false,
    "isTrending": false,
    "score": 92,
    "country": "Ethiopia",
    "lang": "Tigrinya",
    "genre": "Tigrinya Pop",
    "reason": "14.8M views.",
    "spotifyId": "2AlalWAdrCPEXxLrBeEd6U",
    "year": 2025
  },
  {
    "id": "e8",
    "ytId": "HOADb_H4buk",
    "views": 7499191,
    "likes": 48161,
    "comments": 4470,
    "publishedAt": "2025-06-13T14:00:11Z",
    "thumbUrl": "https://i.ytimg.com/vi/HOADb_H4buk/maxresdefault.jpg",
    "youtubeUrl": "https://www.youtube.com/watch?v=HOADb_H4buk",
    "title": "Maeger",
    "artist": "Nguse Abadi",
    "weekViews": 160128,
    "growthRate": 0.0218,
    "rank": 36,
    "prev": 40,
    "isNew": false,
    "isTrending": false,
    "score": 85,
    "country": "Eritrea",
    "lang": "Tigrinya",
    "genre": "Tigrinya Pop",
    "reason": "6.7M views.",
    "spotifyId": null,
    "year": 2025
  },
  {
    "id": "26",
    "ytId": "P9KzCEdCuV4",
    "views": 3187610,
    "likes": 83741,
    "comments": 54650,
    "publishedAt": "2026-04-17T22:05:42Z",
    "thumbUrl": "https://i.ytimg.com/vi/P9KzCEdCuV4/maxresdefault.jpg",
    "youtubeUrl": "https://www.youtube.com/watch?v=P9KzCEdCuV4",
    "title": "Galmee Seenaa",
    "artist": "Gelana Garomsa ft Yosan Getahun",
    "weekViews": 119490,
    "growthRate": 0.0389,
    "rank": 37,
    "prev": 22,
    "isNew": false,
    "isTrending": false,
    "score": 71,
    "country": "Ethiopia",
    "lang": "Oromo",
    "genre": "Oromo Pop",
    "reason": "2.4M views debut week. Already in charts.",
    "spotifyId": null,
    "year": 2026
  },
  {
    "id": "29",
    "rank": 38,
    "prev": 1,
    "isNew": false,
    "title": "Minnow Nesh",
    "artist": "Hachalu Hundessa",
    "country": "Ethiopia",
    "lang": "Oromo",
    "region_language": "Oromo",
    "genre": "Oromo Pop",
    "views": 8200000,
    "weekViews": 0,
    "year": 2021,
    "ytId": "2ixjSHqHqpU",
    "thumbUrl": "https://i.ytimg.com/vi/2ixjSHqHqpU/maxresdefault.jpg",
    "spotifyId": null,
    "reason": "8.2M views — beloved Oromo anthem.",
    "score": 68
  },
  {
    "id": "30",
    "rank": 39,
    "prev": 2,
    "isNew": false,
    "title": "Sabbata",
    "artist": "Dawit Tsige",
    "country": "Ethiopia",
    "lang": "Oromo",
    "region_language": "Oromo",
    "genre": "Oromo Pop",
    "views": 6100000,
    "weekViews": 0,
    "year": 2022,
    "ytId": "Gk6ZkJoFBnE",
    "thumbUrl": "https://i.ytimg.com/vi/Gk6ZkJoFBnE/maxresdefault.jpg",
    "spotifyId": null,
    "reason": "6.1M views — top Oromo pop track.",
    "score": 67
  },
  {
    "id": "31",
    "rank": 40,
    "prev": 4,
    "isNew": false,
    "title": "Siifan Jira",
    "artist": "Caalaa Bultumee",
    "country": "Ethiopia",
    "lang": "Oromo",
    "region_language": "Oromo",
    "genre": "Oromo Pop",
    "views": 4500000,
    "weekViews": 0,
    "year": 2023,
    "ytId": "QxNe3k0b9EU",
    "thumbUrl": "https://i.ytimg.com/vi/QxNe3k0b9EU/maxresdefault.jpg",
    "spotifyId": null,
    "reason": "4.5M views — emotional Oromo ballad.",
    "score": 66
  },
  {
    "id": "e11",
    "rank": 41,
    "prev": 3,
    "isNew": false,
    "title": "Libi Zbele",
    "artist": "Helen Meles",
    "country": "Ethiopia",
    "lang": "Tigrinya",
    "region_language": "Tigrigna",
    "genre": "Tigrinya Pop",
    "views": 4200000,
    "weekViews": 0,
    "year": 2024,
    "ytId": "Q0wH8GVbRfY",
    "thumbUrl": "https://i.ytimg.com/vi/Q0wH8GVbRfY/maxresdefault.jpg",
    "spotifyId": null,
    "reason": "4.2M views.",
    "score": 80
  }
];
